config/routes.rb
Betaman::Application.routes.draw do

  get "dashboard/index"

  get '/users/select', to: 'users#select', as: 'user_select'

  get '/users/:id/betas', to: 'users#betas', as: 'user_betas'
  get '/users/:id/add_beta/:beta_id', to: 'users#add_beta', as: 'user_add_beta'
  get '/users/:id/remove_beta/:beta_id', to: 'users#remove_beta', as: 'user_remove_beta'

  get '/users/emails', to: 'users#emails', as: 'users_emails'

  get '/users/:id/edit_participation/:participation_id', to: 'users#edit_participation', as: 'user_edit_participation'
  post '/users/:id/edit_participation/:participation_id', to: 'users#update_participation', as: 'user_edit_participation'
  get '/users/:id/toggle_participation/:participation_id', to: 'users#toggle_participation', as: 'user_toggle_participation'

  get '/betas/:id/add_select_users', to: 'betas#add_select_users', as: 'beta_add_select_users'
  post '/betas/:id/add_multiple_users', to: 'betas#add_multiple_users', as: 'beta_add_multiple_users'
  get '/betas/:id/add_list_subscribers/:list_id', to: 'betas#add_list_subscribers', as: 'beta_add_list_subscribers'
  get '/betas/:id/add_list/:list_id', to: 'betas#add_list', as: 'beta_add_list'
  get '/betas/:id/remove_list', to: 'betas#remove_list', as: 'beta_remove_list'
  get '/betas/:id/add_user/:user_id', to: 'betas#add_user', as: 'beta_add_user'
  get '/betas/:id/remove_user/:user_id', to: 'betas#remove_user', as: 'beta_remove_user'
  get '/betas/:id/users', to: 'betas#users', as: 'beta_users'
  get '/betas/:id/users_external', to: 'betas#users_external', as: 'beta_users_external'
  get '/betas/:id/join', to: 'betas#join', as: 'beta_join'
  get '/betas/:id/leave', to: 'betas#leave', as: 'beta_leave'

  get '/lists/:id/sync_to_intern', to: 'lists#sync_to_intern', as: 'list_sync_to_intern'
  get '/lists/:id/users', to: 'lists#users', as: 'list_users'
  get '/lists/:id/add_select_users', to: 'lists#add_select_users', as: 'list_add_select_users'
  post '/lists/:id/add_multiple_users', to: 'lists#add_multiple_users', as: 'list_add_multiple_users'
  get '/lists/:id/subscribe_user/:user_id',   to: 'lists#subscribe_user',   as: 'list_subscribe_user'
  get '/lists/:id/unsubscribe_user/:user_id', to: 'lists#unsubscribe_user', as: 'list_unsubscribe_user'

  resources :users
  resources :betas
  resources :lists
  resources :companies

  root to: 'static_pages#home'
  match '/help', to: 'static_pages#help'
  get "static_pages/help"

  match '/dashboard', to:'dashboard#index'

  match '/auth/:provider/callback', :to => 'session#callback'
  match '/auth/failure', :to => 'session#failure'
  match '/auth/:provider/failure', :to => 'session#failure'
  match '/auth/failure', :to => 'session#failure'

  namespace :admin do
    get '/users/duplicate_emails', controller: 'duplicate_emails', as: 'duplicate_emails'
    get '/users/update_roles', controller: 'update_roles', as: 'update_roles'
    get '/betas/sync_downloads', controller: 'sync_downloads', as: 'sync_downloads'
    get '/betas/sync_lists', controller: 'sync_lists', as: 'sync_lists'
    get '/betas/check', controller: 'check', as: 'check'
    get '/betas/inactive_participations', controller: 'inactive_participations', as: 'inactive_participations'
    get '/diary/user/:user_id', to: 'diary#user', as: 'diary_user'
    get '/diary', to: 'diary#index', as: 'diary'
    get '', to: 'dashboard#index', as: '/'
    resources :users 
    resources :betas
    resources :companies

    resources :milestones do
      member do
        get '/add_beta/:beta_id',    to: 'milestones#add_beta',    as: 'add_beta'
        get '/remove_beta/:beta_id', to: 'milestones#remove_beta', as: 'remove_beta'
      end
    end

    resources :groups do
      member do
        post 'upload'
        get '/merge_users', to: 'groups#merge_users', as: 'merge_users'
        get '/groups/:id/users', to: 'groups#users', as: 'users'
        get '/groups/:id/add_user/:user_id', to: 'groups#add_user', as: 'add_user'
        get '/groups/:id/remove_user/:user_id', to: 'groups#remove_user', as: 'remove_user'
        get '/groups/:id/add_select_users',  to: 'groups#add_select_users', as: 'select_users'
        get '/groups/:id/add_to_beta',  to: 'groups#add_to_beta', as: 'add_to_beta'
        post '/groups/:id/add_multiple_users',  to: 'groups#add_multiple_users', as: 'add_multiple_users'
      end
    end
  end
  
  match ':controller/:action' => ":controller#:action"

end

app/models/list.rb
require 'mailmech'

class List < ActiveRecord::Base
  has_many :subscriptions, :dependent => :destroy
  has_many :users, :through => :subscriptions
  belongs_to :beta
  attr_accessible :comment, :name, :pass, :server

  def admin_link
    "#{server}/admin/#{name}"
  end

  def sync_to_intern
    # Sync the external represantation to the internal "real" list
    # (which leaves the external list untouched!)
    mech = Mailmech.new(server,name,pass)

    subscribers = mech.subscribers

    r = { 
      created: [],
      added_to_list: [],
      added_to_beta: [],
      dropped_from_list: []
    }
      
    # Eliminate duplicates
    users.uniq!

    subscribers.map{|s| s.downcase }.each do |s|
      u = User.find_by_email(s)
      if  u
        # Try to add to list
        if !users.include? u
          users << u
          r[:added_to_list] << u
        end
      else
        # Try alternate email
        u = User.find_by_alt_email(s)
        if  u
          if !users.include? u
            users << u
            r[:added_to_list] << u
          end
        else
          # puts "Create user for email #{s} !"
          u = User.new
          u.email = s
          u.note = "User created through\nList sync: #{name}"
          s =~ /(.*)@/
          u.last_name = $1 if $1
          u.save
          users << u
          r[:created] << u
          r[:added_to_list] << u
        end
      end
        
      # Try to add to beta
      if beta && beta.add_user(u)
        r[:added_to_beta] << u 
      end
    end

    users.each do |u|
      email = u.email ||= ""
      alt_email = u.alt_email ||= ""
      if !subscribers.include?(email.downcase) && !subscribers.include?(alt_email.downcase)
        r[:dropped_from_list] << u
      end

    end
    r[:dropped_from_list].each do |u|
      users.delete u
    end

    Blog.info "#{logname} sync_to_intern called:"
    Blog.info "          Created: #{r[:created].map{|u| u.logname}.join(', ')}"
    Blog.info "    Added to list: #{r[:added_to_list].map{|u| u.logname}.join(', ')}"
    Blog.info "    Added to beta: #{r[:added_to_beta].map{|u| u.logname}.join(', ')}"
    Blog.info "          Dropped: #{r[:dropped_from_list].map{|u| u.logname}.join(', ')}"

    return r
  end

  def subscribe(user)
    mech = Mailmech.new(server,name,pass)
    mech.subscribe([user.email])
    Diary.subscribed_user_to_list(user: user, beta: beta)
  end

  def unsubscribe(user)
    mech = Mailmech.new(server,name,pass)
    mech.delete([user.email])
    Diary.unsubscribed_user_from_list(user: user, beta: beta)
  end

  def logname
    if name.nil? || name.empty? 
      return "List #{id}"
    else
      return "List #{id} (#{name})"
    end
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lists }
    end
  end

  def edit
    if @current_user.admin?
      @list = List.find(params[:id])
    else
      flash[:error] = "Access denied: Editing List"
      redirect_to root_path
    end
  end

  def new
    if @current_user.admin?
      @list = List.new
      respond_to do |format|
        format.html 
        format.json { render json: @list }
      end
    else
      flash[:error] = "Access denied: New List"
      redirect_to root_path
    end
  end

  def create
    @list = List.new(params[:list])

    respond_to do |format|
      if @list.save
        msg = "#{@list.logname} created"
        Diary.list_created actor: @current_user, text: "List: #{@list.id} - #{@list.name}"
        flash[:success] = msg
        Blog.info msg, @current_user
        format.html { redirect_to @list }
        format.json { render json: @list, status: :created, location: @list }
      else
        msg = "Failed to create #{@list.logname}"
        flash[:warning] = msg
        Blog.warn msg, @current_user
        format.html { render action: "new" }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @list = List.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @list }
    end
  end

  def update
    @list = List.find(params[:id])

    respond_to do |format|
      if @list.update_attributes(params[:list])
        Diary.list_updated actor: @current_user, text: "List: #{@list.id} - #{@list.name}"
        msg = "Updated list #{@list.logname}"
        flash[:success] = msg
        Blog.info msg, @current_user
        format.html { redirect_to @list }
        format.json { head :no_content }
      else
        msg = "Failed to update list #{@list.logname}"
        flash[:warning] = msg
        Blog.warn msg, @current_user
        format.html { render action: "edit" }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if @current_user.admin?
      list = List.find(params[:id])
      list.destroy
      Diary.list_deleted actor: @current_user, text: "List: #{list.id} - #{list.name}"
      msg = "Deleted #{list.logname}"
      flash[:success] = msg
      Blog.info msg, @current_user

      respond_to do |format|
        format.html { redirect_to lists_url }
        format.json { head :no_content }
      end
    else
      flash[:error] = "Access denied: Delete #{list.logname}"
      redirect_to root_path
    end
  end

  def users
    @list = List.find(params[:id])
    @users = @list.users.order :email
  end

  def sync_to_intern
    list = List.find(params[:id])
    r = list.sync_to_intern
    if r[:added_to_list].count > 0 || r[:created].count > 0
      flash[:success] = "#{r[:added_to_list].count} users added to internal list, #{r[:created].count} of them created new"
    end
    if r[:dropped_from_list].count > 0
      flash[:warning] = "#{r[:dropped_from_list].count} users dropped from internal list"
    end

    redirect_to :back
  end

  def add_select_users
    @list = List.find(params[:id])
    @nousers = []
    if @current_user.admin? 
      @nousers = User.all
    end
  end

  def add_multiple_users
    @list = List.find(params[:id])
    if @current_user.admin? 
      if defined?(params[:user_ids])
        added = []
        params[:user_ids].each do |user|
          u = User.find(user)
          if u
            @list.users << u
            added << u.logname
          end
        end

        n = added.count
        s = view_context.pluralize(n, 'subscriber')
        msg = "Added #{s} to #{@list.name}: #{added.join(", ")}"
        flash[:success] = msg
        Blog.info msg, @current_user
      else
        flash[:warning] = "No Params defined"
      end
    end
    redirect_to list_path(@list)
  end

  def subscribe_user
    if @current_user.admin? 
      list = List.find(params[:id])
      user = User.find(params[:user_id])
      list.subscribe(user)
      listchanges = list.sync_to_intern
      if listchanges[:added_to_list].include? user

        msg = "Subscribed #{user.logname} to #{list.name}"
        flash[:success] = msg
        Blog.info msg, @current_user
        Diary.subscribed_user_to_list user: user, list: list, actor: @current_user
      else
        msg = "Subscribing #{user.email} to #{list.name} failed"
        flash[:error] = msg
        Blog.warn msg, @current_user
      end
    end
    redirect_to :back
  end

  def unsubscribe_user
    if @current_user.admin? 
      list = List.find(params[:id])
      user = User.find(params[:user_id])
      list.unsubscribe(user)
      listchanges = list.sync_to_intern
      if listchanges[:dropped_from_list].include? user
        msg = "Unsubscribed #{user.logname} from #{list.logname}"
        flash[:success] = msg
        Blog.info msg, @current_user
      else
        msg = "Unsubscribing #{user.email} from #{list.logname} failed"
        flash[:error] = msg
        Blog.warn msg, @current_user
        Diary.unsubscribed_user_from_list user: user, list: list, actor: @current_user
      end
    end
    redirect_to :back
  end
end

app/views/lists/_form.html.haml
= form_for @list do |f|
  - if @list.errors.any?
    #error_explanation
      %h2= "#{pluralize(@list.errors.count, "error")} prohibited this list from being saved:"
      %ul
        - @list.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :server
    = f.text_field :server
  .field
    = f.label 'Password'
    = f.text_field :pass

  .field

  .actions
    = f.submit 'Save', class: 'btn btn-success'

app/views/lists/add_select_users.html.haml
=link_to "#{@list.name}", lists_path(@list), class: 'btn'

%br
%br
=render partial: 'shared/users_select', locals:{ path: list_add_multiple_users_path(@list), userlist: @nousers, submitname: 'Add subscribers' }

app/views/lists/index.html.haml
%h4 Lists:

- if @current_user.admin?
  = link_to new_list_path, class: 'btn btn-mini btn-success ' do
    %i.icon-plus
    Create list
  %br
  %br

%table.table.table-bordered
  %tr
    %th Name
    %th Beta
    - if @current_user.admin? || @current_user.employee?
      %th Subscribers
    - if @current_user.admin?
      %th Admin

  - @lists.each do |list|
    %tr
      %td= link_to(list.name, list ) 
      %td
        - if list.beta
          =link_to list.beta.name, beta_path(list.beta)
      - if @current_user.admin? || @current_user.employee?
        %td
          = link_to(list_users_path(list)) do
            =list.users.count
            - if list.users.count > 0
              %i.icon-eye-open
      - if @current_user.admin?
        %td
          =link_to(list_sync_to_intern_path(list)) do
            %i.icon-refresh 
          = link_to(edit_list_path(list), :title => 'Edit') do
            %i{:class => ['icon-red', 'icon-pencil']}
          = link_to(list, :title => 'Delete', :method => :delete, :data => { :confirm => 'Are you sure?' }) do
            %i.icon-trash

app/views/lists/new.html.haml
%h4 Create list:
= render 'form'

app/views/lists/show.html.haml
=link_to "List: #{@list.name}", list_path(@list), class: 'btn'

%table
  %tr
    %td.right.bold.top
      Mailman:
    %td
      = link_to (@list.admin_link) do
        =@list.admin_link

  %tr
    %td.right.bold.top
      Subscribers:
    %td
      = @list.subscriptions.count

  %tr
    %td.right.bold.top
      Beta:
    %td
      - if @list.beta
        = link_to(@list.beta.name, beta_path(@list.beta))


-#
  = "#{@users.count} total, #{pluralize(@users.admins.count, 'admin')}, "
  = "#{pluralize(@users.employees.count, 'employee')}, "
  = "#{pluralize(@users.testers.count, 'tester')}"

%div{ class: 'btn-group'}
  = if @current_user.admin?
    = link_to 'Sync ext -> int', list_sync_to_intern_path(@list),  class: 'btn btn-mini btn-danger' 
    - if @list.beta
      = link_to(beta_add_list_subscribers_path(@list.beta, @list.id), class: 'btn btn-mini btn-danger' ) do
        = "Add (int) subscribers to #{@list.beta.name}"
    = link_to 'Edit', edit_list_path(@list),  class: 'btn btn-mini btn-info' 
    = link_to 'Add subscriber (int)', list_add_select_users_path,  class: 'btn btn-mini btn-info' 
  = if @current_user.employee?
    = link_to 'Show subscribers (int)', list_users_path(@list), class: 'btn btn-mini btn-info' 

app/views/lists/users.html.haml
=link_to "#{@list.name}", list_path(@list), class: 'btn'
%h4 Subscriptions:

%table.table.table-bordered
  %tr
    %th Name
    %th Email
    %th Betas
    - if @current_user.admin?
      %th Actions

  - @users.each do |user|
    %tr
      %td
        - if @current_user.admin?
          = link_to user.full_name, edit_user_path(user)
        - else
          = link_to user.full_name, user
      %td= mail_to user.email
      %td
        = link_to(user_betas_path(user) ) do
          =user.betas.count
          - if user.betas.count > 0
            %i.icon-eye-open
      - if @current_user.admin?
        %td
          = link_to(edit_user_path(user)) do
            .i.icon-pencil
          - if @beta
            = link_to(beta_remove_user_path(@beta, user_id: user) ) do
              .i.icon-trash
          - else
            = link_to(list_unsubscribe_user_path(@list, user_id: user), :data => { :confirm => 'Are you sure?' } ) do
              .i.icon-trash