config/routes.rb
Betaman::Application.routes.draw do

  get "dashboard/index"

  get '/users/select', to: 'users#select', as: 'user_select'

  get '/users/:id/betas', to: 'users#betas', as: 'user_betas'
  get '/users/:id/add_beta/:beta_id', to: 'users#add_beta', as: 'user_add_beta'
  get '/users/:id/remove_beta/:beta_id', to: 'users#remove_beta', as: 'user_remove_beta'

  get '/users/emails', to: 'users#emails', as: 'users_emails'

  get '/users/:id/edit_participation/:participation_id', to: 'users#edit_participation', as: 'user_edit_participation'
  post '/users/:id/edit_participation/:participation_id', to: 'users#update_participation', as: 'user_edit_participation'
  get '/users/:id/toggle_participation/:participation_id', to: 'users#toggle_participation', as: 'user_toggle_participation'

  get '/betas/:id/add_select_users', to: 'betas#add_select_users', as: 'beta_add_select_users'
  post '/betas/:id/add_multiple_users', to: 'betas#add_multiple_users', as: 'beta_add_multiple_users'
  get '/betas/:id/add_list_subscribers/:list_id', to: 'betas#add_list_subscribers', as: 'beta_add_list_subscribers'
  get '/betas/:id/add_list/:list_id', to: 'betas#add_list', as: 'beta_add_list'
  get '/betas/:id/remove_list', to: 'betas#remove_list', as: 'beta_remove_list'
  get '/betas/:id/add_user/:user_id', to: 'betas#add_user', as: 'beta_add_user'
  get '/betas/:id/remove_user/:user_id', to: 'betas#remove_user', as: 'beta_remove_user'
  get '/betas/:id/users', to: 'betas#users', as: 'beta_users'
  get '/betas/:id/users_external', to: 'betas#users_external', as: 'beta_users_external'
  get '/betas/:id/join', to: 'betas#join', as: 'beta_join'
  get '/betas/:id/leave', to: 'betas#leave', as: 'beta_leave'

  get '/lists/:id/sync_to_intern', to: 'lists#sync_to_intern', as: 'list_sync_to_intern'
  get '/lists/:id/users', to: 'lists#users', as: 'list_users'
  get '/lists/:id/add_select_users', to: 'lists#add_select_users', as: 'list_add_select_users'
  post '/lists/:id/add_multiple_users', to: 'lists#add_multiple_users', as: 'list_add_multiple_users'
  get '/lists/:id/subscribe_user/:user_id',   to: 'lists#subscribe_user',   as: 'list_subscribe_user'
  get '/lists/:id/unsubscribe_user/:user_id', to: 'lists#unsubscribe_user', as: 'list_unsubscribe_user'

  resources :users
  resources :betas
  resources :lists
  resources :companies

  root to: 'static_pages#home'
  match '/help', to: 'static_pages#help'
  get "static_pages/help"

  match '/dashboard', to:'dashboard#index'

  match '/auth/:provider/callback', :to => 'session#callback'
  match '/auth/failure', :to => 'session#failure'
  match '/auth/:provider/failure', :to => 'session#failure'
  match '/auth/failure', :to => 'session#failure'

  namespace :admin do
    get '/users/duplicate_emails', controller: 'duplicate_emails', as: 'duplicate_emails'
    get '/users/update_roles', controller: 'update_roles', as: 'update_roles'
    get '/betas/sync_downloads', controller: 'sync_downloads', as: 'sync_downloads'
    get '/betas/sync_lists', controller: 'sync_lists', as: 'sync_lists'
    get '/betas/check', controller: 'check', as: 'check'
    get '/betas/inactive_participations', controller: 'inactive_participations', as: 'inactive_participations'
    get '/diary/user/:user_id', to: 'diary#user', as: 'diary_user'
    get '/diary', to: 'diary#index', as: 'diary'
    get '', to: 'dashboard#index', as: '/'
    resources :users 
    resources :betas
    resources :companies

    resources :milestones do
      member do
        get '/add_beta/:beta_id',    to: 'milestones#add_beta',    as: 'add_beta'
        get '/remove_beta/:beta_id', to: 'milestones#remove_beta', as: 'remove_beta'
      end
    end

    resources :groups do
      member do
        post 'upload'
        get '/merge_users', to: 'groups#merge_users', as: 'merge_users'
        get '/groups/:id/users', to: 'groups#users', as: 'users'
        get '/groups/:id/add_user/:user_id', to: 'groups#add_user', as: 'add_user'
        get '/groups/:id/remove_user/:user_id', to: 'groups#remove_user', as: 'remove_user'
        get '/groups/:id/add_select_users',  to: 'groups#add_select_users', as: 'select_users'
        get '/groups/:id/add_to_beta',  to: 'groups#add_to_beta', as: 'add_to_beta'
        post '/groups/:id/add_multiple_users',  to: 'groups#add_multiple_users', as: 'add_multiple_users'
      end
    end
  end
  
  match ':controller/:action' => ":controller#:action"

end

app/models/beta.rb
require 'betaadmin'

class Beta < ActiveRecord::Base
  attr_accessible :begin, :end, 
    :name, :alias, 
    :novell_id, :novell_user, :novell_pass, :novell_iw_user, :novell_iw_pass, 
    :downloadLocationInt, :downloadLocationExt

  has_many :participations, :dependent => :destroy
  has_many :users, :through => :participations

  has_many :miles, :dependent => :destroy
  has_many :milestones, :through => :miles

  has_many :urllinks, :dependent => :destroy
  has_many :urls, :through => :urllinks

  has_one :list

  default_scope -> { order('begin DESC') }

  scope :active, lambda { where('? BETWEEN betas.begin AND betas.end', Date.today ) }
  scope :planned, lambda { where('betas.begin > ?', Date.today) }
  scope :finished, lambda { where('betas.end < ?', Date.today) }
  scope :not_finished, lambda { where('betas.end >= ?', Date.today) }

  def add_user(user, actor = nil)
    if !self.users.include? user
      self.users << user
      Diary.added_user_to_beta user: user, beta: self, actor: actor
      return true
    end
    return false
  end

  def add_users(userlist)
    added = []
    existing = []
    userlist.each do |user|
     if add_users user
        added << user.email
      else
        existing << user.email
      end
    end
    return added, existing
  end

  def remove_user(user, actor = nil)
    if self.users.include? user
      self.users.delete  user
      Diary.removed_user_from_beta user: user, beta: self, actor: actor
      return true
    end
    return false
  end

  def logname
    "#{id} (#{name})"
  end

  def has_novell_download?
    return !(novell_user.blank? || 
             novell_pass.blank? || 
             novell_iw_user.blank? ||
             novell_iw_pass.blank? ||
             novell_id.blank?)
  end
end

app/controllers/admin/betas_controller.rb
require 'betaadmin'
require 'download_helper'

class Admin::BetasController < ApplicationController
  def index
    if !@current_user.admin?
      redirect_to root_path
    end
    
    @betas = Beta.all
    @active_betas = Beta.active
    @planned_betas = Beta.planned
    @finished_betas = Beta.finished
  end

  def sync_downloads
    ba = BetaAdmin.new
    user =Beta.find(1).novell_iw_user #FIXME use ID of beta listed in Innerweb
    pass =Beta.find(1).novell_iw_pass #FIXME use ID of beta listed in Innerweb
    if !ba.login_innerweb(Beta.find(1).novell_iw_user, Beta.find(1).novell_iw_pass)
      msg = "Could not login to Innerweb as user #{user}"
      Blog.info msg, @current_user
      flash[:error] = msg
      redirect_to admin_path
      return
    end

    @betas_with_downloads = DownloadHelper.find_betas_with_downloads
    @betas_with_downloads.each do |b|
      r = ba.sync_downloads b[:beta]
      b[:added] = r[:added]
      b[:dropped] = r[:dropped]
    end
  end

  def sync_lists
    # Find betas with lists
    @betas_with_lists = []
    Beta.all.each do |b|
      if !b.list.blank?
        r = b.list.sync_to_intern
        @betas_with_lists << { 
          beta: b, 
          added_to_list: r[:added_to_list], 
          dropped_from_list: r[:dropped_from_list], 
          created: r[:created],
          added_to_beta: r[:added_to_beta]
        }
      end
    end
  end

  def check
    # Find betas with downloads
    @betas_with_downloads = DownloadHelper.find_betas_with_downloads
  end

  def inactive_participations
  end
end

app/controllers/betas_controller.rb
class BetasController < ApplicationController
  def index
    @betas = Beta.all
    @active_betas = Beta.active
    @planned_betas = Beta.planned
    @finished_betas = Beta.finished

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @betas }
    end
  end

  def edit
    if @current_user.admin?
      @beta = Beta.find(params[:id])

    else
      flash[:error] = "Access denied: Editing Beta test"
      redirect_to root_path
    end
  end

  def new
    if @current_user.admin?
      beta = Beta.new
      beta.name  = "New beta"
      beta.begin = Date.today
      beta.end   = Date.today

      if beta.save!
        Blog.info "Created new beta #{beta.id}", @current_user
        redirect_to edit_beta_path(beta)
      else
        Blog.error "Creating new beta failed", @current_user
        redirect_to root_path(beta)
      end
    else
      flash[:error] = "Access denied: New Beta test"
      redirect_to root_path
    end
  end

  def create
    @beta = Beta.new(params[:beta])

    respond_to do |format|
      if @beta.save
        msg = "Created beta #{@beta.name}"
        flash[:success] = msg
        Blog.info msg, @current_user
        format.html { redirect_to @beta }
        format.json { render json: @beta, status: :created, location: @beta }
      else
        flash[:warning] = "Failed to create beta #{@beta.name}"
        format.html { render action: "new" }
        format.json { render json: @beta.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @beta = Beta.find(params[:id])
    @users = @beta.users
    @milestones = @beta.milestones.order('date ASC')
    @urls = @beta.urls

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @beta }
    end
  end

  def update
    @beta = Beta.find(params[:id])

    respond_to do |format|
      if @beta.update_attributes(params[:beta])
        msg = "Updated beta #{@beta.name}"
        flash[:success] = msg
        Blog.info msg, @current_user

        format.html { redirect_to @beta }
        format.json { head :no_content }
      else
        flash[:warning] = "Failed to update beta #{@beta.name}"
        format.html { render action: "edit" }
        format.json { render json: @beta.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if @current_user.admin?
      @beta = Beta.find(params[:id])
      msg = "#{@beta.name} deleted"
      flash[:success] = msg
      Blog.info msg, @current_user

      @beta.destroy

      respond_to do |format|
        format.html { redirect_to betas_url }
        format.json { head :no_content }
      end
    else
      flash[:error] = "Access denied: Delete Beta test"
      redirect_to root_path
    end
  end

  def users
    @beta = Beta.find(params[:id])
    @users = @beta.users
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: UsersDatatable.new(view_context, {users: @users} ) }
    end
  end

  def users_external
    @beta = Beta.find(params[:id])
    @users = @beta.users.external
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: UsersDatatable.new(view_context, {users: @users} ) }
    end
  end

  def init_nousers
    @nousers = User.all - @beta.users
  end

  def add_user
    @beta = Beta.find(params[:id])
    user = User.find(params[:user_id])

    if @current_user.admin?
      if @beta.add_user user, @current_user
        msg = "Added #{user.full_name} to #{@beta.name}"
        flash[:success] = msg
        Blog.info msg, @current_user
      else
        flash[:warning] = "#{user.full_name} is already member of #{@beta.name}"
      end

      redirect_to :back
    end
  end

  def add_select_users
    @beta = Beta.find(params[:id])
    @nousers = init_nousers
  end

  def add_multiple_users
    @beta = Beta.find(params[:id])
    if @current_user.admin? 
      if defined?(params[:user_ids])
        n = params[:user_ids].count
        s = view_context.pluralize(n, 'participant')

        ulist = []
        params[:user_ids].each do |user|
          u = User.find(user)
          if (u)
            @beta.users << u
            ulist << "#{u.id} (#{u.email})"
            Diary.added_user_to_beta user: u, beta: @beta, actor: @current_user
          end
        end
        flash[:success] = "Added #{s} to #{@beta.name}"
        Blog.info "Added to #{@beta.name}: #{ulist.join(',')}", @current_user
      else
        flash[:warning] = "No Params defined"
      end
    end
    redirect_to beta_path(@beta)
  end

  def add_list_subscribers
    @beta = Beta.find(params[:id])
    list = List.find(params[:list_id])
    if @current_user.admin? && list && @beta
      added, existing = @beta.add_users(list.users)
      all_count   = view_context.pluralize(list.users.count, 'subscriber')
      added_count = view_context.pluralize(added.count, 'participant')
      exist_count = view_context.pluralize(existing.count, 'participant')
      flash[:success] = "Added #{added_count} to #{@beta.name}, found already #{exist_count}."
      UserMailer.admin_mail(
        "Added #{added_count} from #{list.name} to beta #{@beta.name}",
        "Beta: #{@beta.name}\n" +
        "List: #{list.name}\n\n" +
        "request to add #{all_count} resulted in \n" +
        "  #{added_count} added (see below) and\n" +
        "  #{exist_count} already existing\n\n" +
        added.join("\n")
      ).deliver
      Blog.info "Adding list subscribers from #{list.name} to #{@beta.name}:", @current_user
      added.each {|u| Blog.info "  Added: #{u}"}
    end
    redirect_to beta_path(@beta)
  end

  def remove_user
    @beta = Beta.find(params[:id])

    user = User.find(params[:user_id])

    if @current_user.admin?
      if @beta.remove_user user, @current_user
        msg = "Removed #{user.full_name} from #{@beta.name}"
        flash[:success] = msg
        Blog.info msg, @current_user
      else
        flash[:warning] = "User #{user.full_name} is not a member of beta #{@beta.logname}!"
      end
      redirect_to :back
    end
  end

  def add_list
    if @current_user.admin?
      beta = Beta.find(params[:id])
      newlist = List.find(params[:list_id])
      if beta.list
        flash[:error] = "#{beta.name} already has a list named #{beta.list.name}"
      else
        beta.list = newlist
        msg = "Added list #{newlist.name} to #{beta.name}"
        flash[:success] = msg
        Blog.info msg, @current_user
      end
    end
    redirect_to :back
  end

  def remove_list
    if @current_user.admin?
      beta = Beta.find(params[:id])
      if beta.list
        msg = "Removed list #{beta.list.name} from  #{beta.name}"
        flash[:success] = msg
        Blog.info msg, @current_user
        beta.list = nil
      else
        flash[:error] = "#{beta.name} has no mailing list"
      end
    end
    redirect_to :back
  end

  def join
    @beta = Beta.find(params[:id])
    if !@beta.users.include? @current_user
      msg = "Added #{@current_user.full_name} to #{@beta.name}"
      flash[:success] = msg
      @beta.users << @current_user
      Blog.info msg, @current_user
      UserMailer.admin_mail(
        "User #{@current_user.logname} joined Beta #{@beta.name}",
        "    email: #{@current_user.email}\n" +
        "     name: #{@current_user.full_name}\n" +
        "       ID: #{@current_user.id}\n" +
        "Please adjust list subscriptions manually").deliver
    end
    Diary.joined_beta user: @current_user, beta: @beta

    redirect_to :back
  end

  def leave
    @beta = Beta.find(params[:id])
    if @beta.users.include? @current_user
      flash[:success] = "Removed user #{@current_user.full_name} from #{@beta.name}"
      @beta.users.delete @current_user
      Blog.info "#{@current_user.logname} left #{@beta.name}", @current_user

      UserMailer.admin_mail(
        "User #{@current_user.logname} left Beta #{@beta.name}",
        "    email: #{@current_user.email}\n" +
        "     name: #{@current_user.full_name}\n" +
        "       ID: #{@current_user.id}\n" +
        "Please adjust list subscriptions manually").deliver
    end

    Diary.left_beta user: @current_user, beta: @beta

    redirect_to :back
  end
end

app/helpers/betas_helper.rb
module BetasHelper
end

app/views/admin/betas/check.html.haml
%h4 Betas with downloads:

%ul
  - @betas_with_downloads.each do |b|
    %li
      %p
        %h4= link_to b[:beta].name, beta_path(b[:beta])

    %p  
      -# External users without downloads
      - if b[:ext_users_without_downloads].count == 0
        %b= "#{b[:ext_users_without_downloads].count} external users without downloads" 
      -else
        .warning-red
          %b= "#{b[:ext_users_without_downloads].count} external users without downloads" 
          <input id="toggle-dldetails-#{b[:beta].id}" type="button" value="Details" />
        %div{:id => "dldetails-#{b[:beta].id}"}
          %ul
            - b[:ext_users_without_downloads].each do |u|
              %li
                =link_to u.full_name, edit_user_path(u)
                = "- #{u.email}"
                - if !b[:ext_users_without_list].include? u
                  .warning-red
                    Warning: already subscribed to list!
        :javascript
          $(document).ready(function() {
            $("#dldetails-#{b[:beta].id}").hide();
            $("#toggle-dldetails-#{b[:beta].id}").click(function() {
              $("#dldetails-#{b[:beta].id}").toggle("normal");
            });
          });

    %p  
      -# External users without support requested
      - if b[:ext_users_with_downloads_nosupport].count == 0
        %b= "#{b[:ext_users_with_downloads_nosupport].count} external users with downloads, but missing support" 
      - else
        .warning-red
          %b= "#{b[:ext_users_with_downloads_nosupport].count} external users with downloads, but missing support" 
          <input id="toggle-support-details-#{b[:beta].id}" type="button" value="Details" />
        %div{:id => "support-details-#{b[:beta].id}"}
          %ul
            - b[:ext_users_with_downloads_nosupport].each do |u|
              %li
                =link_to u.full_name, edit_user_path(u)
                = "- #{u.email}"
        :javascript
          $(document).ready(function() {
            $("#support-details-#{b[:beta].id}").hide();
            $("#toggle-support-details-#{b[:beta].id}").click(function() {
              $("#support-details-#{b[:beta].id}").toggle("normal");
            });
          });

    %p
      -# External users without mailing list subscription
      - if b[:ext_users_without_list].count == 0 
        %b= "#{b[:ext_users_without_list].count} external users without list subscription" 
      - else
        .warning-red
          = "#{b[:ext_users_without_list].count} external users without list subscription" 
          <input id="toggle-listdetails-#{b[:beta].id}" type="button" value="Details" />
        %div{:id => "listdetails-#{b[:beta].id}"}
          %ul
            - b[:ext_users_without_list].each do |u|
              %li
                =link_to u.full_name, edit_user_path(u)
                = "- #{u.email}"
        :javascript
          $(document).ready(function() {
            $("#listdetails-#{b[:beta].id}").hide();
            $("#toggle-listdetails-#{b[:beta].id}").click(function() {
              $("#listdetails-#{b[:beta].id}").toggle("normal");
            });
          });

    %p
      -# Internal users without mailing list subscription
      - if b[:int_users_without_list].count == 0
        %b= "#{b[:int_users_without_list].count} internal users without list subscription" 
      - else
        .warning-red
          %b= "#{b[:int_users_without_list].count} internal users without list subscription" 
          <input id="toggle-int-listdetails-#{b[:beta].id}" type="button" value="Details" />
        %div{:id => "int-listdetails-#{b[:beta].id}"}
          %ul
            - b[:int_users_without_list].each do |u|
              %li
                =link_to u.full_name, edit_user_path(u)
                = "- #{u.email}"
        :javascript
          $(document).ready(function() {
            $("#int-listdetails-#{b[:beta].id}").hide();
            $("#toggle-int-listdetails-#{b[:beta].id}").click(function() {
              $("#int-listdetails-#{b[:beta].id}").toggle("normal");
            });
          });
%br
%br
%p
  =link_to "Back to admin dashboard", admin_path, class: 'btn'

app/views/admin/betas/inactive_participations.html.haml
%h4 Inactive participations
%ul
  - Beta.order(:id).each do |beta|
    - participations =  beta.participations.where(:active => false)
    - if participations.count > 0
      %li
        %h5= beta.name
        %ul
          - participations.each do |p|
            %li 
              = link_to p.user.full_name, user_path(p.user)
              \-
              = mail_to p.user.email
        
%br
%br
%p
  =link_to "Back to admin dashboard", admin_path, class: 'btn'

app/views/admin/betas/index.html.haml
=render partial: "shared/beta_list", locals:{ show_actions: false, betas: @planned_betas, title: 'Planned' }
=render partial: "shared/beta_list", locals:{ show_actions: false, betas: @active_betas, title: 'Active' }
=render partial: "shared/beta_list", locals:{ show_actions: false, betas: @finished_betas, title: 'Finished' }
%br

- if @current_user && @current_user.admin?
  = link_to(new_beta_path, class: 'btn btn-info btn-mini') do
    %i{class: ["icon-plus", " icon-large"]}
    Add new beta test

app/views/admin/betas/sync_downloads.html.haml
%h4 Updated internal download lists:

- @betas_with_downloads.each do |b|
  %h5= link_to b[:beta].name, beta_path(b[:beta])
  %table
    %tr
      %td.right Participations:
      %td= b[:beta].participations.count
    %tr
      %td.right.top Downloads added:
      - if b[:added].count == 0
        %td -
      - else
        %td
          %table
            - b[:added].each do |u|
              %tr
                %td= link_to u.logname, edit_user_path(u)

    %tr
      %td.right.top Downloads dropped:
      - if b[:dropped].count == 0
        %td -
      - else
        %td
          %table
            - b[:dropped].each do |u|
              %tr
                %td= link_to u.logname, edit_user_path(u)

%br
%br
%p
  =link_to "Back to admin dashboard", admin_path, class: 'btn'

app/views/admin/betas/sync_lists.html.haml
%h4 Updated internal mailing lists:

%ul
- @betas_with_lists.each do |b|
  %li
    = link_to b[:beta].name, beta_path(b[:beta])
    - if b[:created].count > 0
      %p 
        Created:
        %ul
          - b[:created].each do |u|
            %li= link_to( u.logname, edit_user_path(u))
    - if b[:added_to_list].count > 0
      %p 
        Added to list:
        %ul
          - b[:added_to_list].each do |u|
            %li= link_to( u.logname, edit_user_path(u))
    - if b[:dropped_from_list].count > 0
      %p
        Dropped:
        %ul
          - b[:dropped_from_list].each do |u|
            %li= link_to( u.logname, edit_user_path(u))
    - if b[:added_to_beta].count > 0
      %p
        Added to beta:
        %ul
          - b[:added_to_beta].each do |u|
            %li= link_to( u.logname, edit_user_path(u))
%br
%br
%p
  =link_to "Back to admin dashboard", admin_path, class: 'btn'